/*
 * Generated by Bluespec Compiler, version 2014.07.A (build 34078, 2014-07-30)
 * 
 * On Sun Jun  4 10:57:43 CST 2017
 * 
 */
#ifndef __vpi_wrapper_matchtable_read_pipeline_rewind_rewind_table_h__
#define __vpi_wrapper_matchtable_read_pipeline_rewind_rewind_table_h__

#include <vpi_user.h>

/* registration function */
void matchtable_read_pipeline_rewind_rewind_table_vpi_register();

/* VPI wrapper function */
PLI_INT32 matchtable_read_pipeline_rewind_rewind_table_calltf(PLI_BYTE8 *user_data);

#endif /* ifndef __vpi_wrapper_matchtable_read_pipeline_rewind_rewind_table_h__ */
