//
// Generated by Bluespec Compiler, version 2014.07.A (build 34078, 2014-07-30)
//
// On Thu Jun  1 22:52:11 CST 2017
//
// BVI format method schedule info:
// schedule prev_0_enq  CF ( prev_1_enq,
// 			  prev_2_enq,
// 			  prev_3_enq,
// 			  next_0_first,
// 			  next_0_deq,
// 			  next_0_notEmpty,
// 			  next_1_first,
// 			  next_1_deq,
// 			  next_1_notEmpty,
// 			  next_2_first,
// 			  next_2_deq,
// 			  next_2_notEmpty,
// 			  next_3_first,
// 			  next_3_deq,
// 			  next_3_notEmpty,
// 			  set_verbosity );
// schedule prev_0_enq  C ( prev_0_enq );
//
// schedule prev_0_notFull  CF ( prev_0_notFull,
// 			      prev_1_notFull,
// 			      prev_2_notFull,
// 			      prev_3_notFull,
// 			      next_0_first,
// 			      next_0_deq,
// 			      next_0_notEmpty,
// 			      next_1_first,
// 			      next_1_deq,
// 			      next_1_notEmpty,
// 			      next_2_first,
// 			      next_2_deq,
// 			      next_2_notEmpty,
// 			      next_3_first,
// 			      next_3_deq,
// 			      next_3_notEmpty,
// 			      set_verbosity );
// schedule prev_0_notFull  SBR ( prev_0_enq,
// 			       prev_1_enq,
// 			       prev_2_enq,
// 			       prev_3_enq );
//
// schedule prev_1_enq  CF ( prev_0_enq,
// 			  prev_2_enq,
// 			  prev_3_enq,
// 			  next_0_first,
// 			  next_0_deq,
// 			  next_0_notEmpty,
// 			  next_1_first,
// 			  next_1_deq,
// 			  next_1_notEmpty,
// 			  next_2_first,
// 			  next_2_deq,
// 			  next_2_notEmpty,
// 			  next_3_first,
// 			  next_3_deq,
// 			  next_3_notEmpty,
// 			  set_verbosity );
// schedule prev_1_enq  C ( prev_1_enq );
//
// schedule prev_1_notFull  CF ( prev_0_notFull,
// 			      prev_1_notFull,
// 			      prev_2_notFull,
// 			      prev_3_notFull,
// 			      next_0_first,
// 			      next_0_deq,
// 			      next_0_notEmpty,
// 			      next_1_first,
// 			      next_1_deq,
// 			      next_1_notEmpty,
// 			      next_2_first,
// 			      next_2_deq,
// 			      next_2_notEmpty,
// 			      next_3_first,
// 			      next_3_deq,
// 			      next_3_notEmpty,
// 			      set_verbosity );
// schedule prev_1_notFull  SBR ( prev_0_enq,
// 			       prev_1_enq,
// 			       prev_2_enq,
// 			       prev_3_enq );
//
// schedule prev_2_enq  CF ( prev_0_enq,
// 			  prev_1_enq,
// 			  prev_3_enq,
// 			  next_0_first,
// 			  next_0_deq,
// 			  next_0_notEmpty,
// 			  next_1_first,
// 			  next_1_deq,
// 			  next_1_notEmpty,
// 			  next_2_first,
// 			  next_2_deq,
// 			  next_2_notEmpty,
// 			  next_3_first,
// 			  next_3_deq,
// 			  next_3_notEmpty,
// 			  set_verbosity );
// schedule prev_2_enq  C ( prev_2_enq );
//
// schedule prev_2_notFull  CF ( prev_0_notFull,
// 			      prev_1_notFull,
// 			      prev_2_notFull,
// 			      prev_3_notFull,
// 			      next_0_first,
// 			      next_0_deq,
// 			      next_0_notEmpty,
// 			      next_1_first,
// 			      next_1_deq,
// 			      next_1_notEmpty,
// 			      next_2_first,
// 			      next_2_deq,
// 			      next_2_notEmpty,
// 			      next_3_first,
// 			      next_3_deq,
// 			      next_3_notEmpty,
// 			      set_verbosity );
// schedule prev_2_notFull  SBR ( prev_0_enq,
// 			       prev_1_enq,
// 			       prev_2_enq,
// 			       prev_3_enq );
//
// schedule prev_3_enq  CF ( prev_0_enq,
// 			  prev_1_enq,
// 			  prev_2_enq,
// 			  next_0_first,
// 			  next_0_deq,
// 			  next_0_notEmpty,
// 			  next_1_first,
// 			  next_1_deq,
// 			  next_1_notEmpty,
// 			  next_2_first,
// 			  next_2_deq,
// 			  next_2_notEmpty,
// 			  next_3_first,
// 			  next_3_deq,
// 			  next_3_notEmpty,
// 			  set_verbosity );
// schedule prev_3_enq  C ( prev_3_enq );
//
// schedule prev_3_notFull  CF ( prev_0_notFull,
// 			      prev_1_notFull,
// 			      prev_2_notFull,
// 			      prev_3_notFull,
// 			      next_0_first,
// 			      next_0_deq,
// 			      next_0_notEmpty,
// 			      next_1_first,
// 			      next_1_deq,
// 			      next_1_notEmpty,
// 			      next_2_first,
// 			      next_2_deq,
// 			      next_2_notEmpty,
// 			      next_3_first,
// 			      next_3_deq,
// 			      next_3_notEmpty,
// 			      set_verbosity );
// schedule prev_3_notFull  SBR ( prev_0_enq,
// 			       prev_1_enq,
// 			       prev_2_enq,
// 			       prev_3_enq );
//
// schedule next_0_first  CF ( prev_0_enq,
// 			    prev_0_notFull,
// 			    prev_1_enq,
// 			    prev_1_notFull,
// 			    prev_2_enq,
// 			    prev_2_notFull,
// 			    prev_3_enq,
// 			    prev_3_notFull,
// 			    next_0_first,
// 			    next_0_notEmpty,
// 			    next_1_first,
// 			    next_1_deq,
// 			    next_1_notEmpty,
// 			    next_2_first,
// 			    next_2_deq,
// 			    next_2_notEmpty,
// 			    next_3_first,
// 			    next_3_deq,
// 			    next_3_notEmpty,
// 			    set_verbosity );
// schedule next_0_first  SB ( next_0_deq );
//
// schedule next_0_deq  CF ( prev_0_enq,
// 			  prev_0_notFull,
// 			  prev_1_enq,
// 			  prev_1_notFull,
// 			  prev_2_enq,
// 			  prev_2_notFull,
// 			  prev_3_enq,
// 			  prev_3_notFull,
// 			  next_1_first,
// 			  next_1_deq,
// 			  next_1_notEmpty,
// 			  next_2_first,
// 			  next_2_deq,
// 			  next_2_notEmpty,
// 			  next_3_first,
// 			  next_3_deq,
// 			  next_3_notEmpty,
// 			  set_verbosity );
// schedule next_0_deq  C ( next_0_deq );
//
// schedule next_0_notEmpty  CF ( prev_0_enq,
// 			       prev_0_notFull,
// 			       prev_1_enq,
// 			       prev_1_notFull,
// 			       prev_2_enq,
// 			       prev_2_notFull,
// 			       prev_3_enq,
// 			       prev_3_notFull,
// 			       next_0_first,
// 			       next_0_notEmpty,
// 			       next_1_first,
// 			       next_1_deq,
// 			       next_1_notEmpty,
// 			       next_2_first,
// 			       next_2_deq,
// 			       next_2_notEmpty,
// 			       next_3_first,
// 			       next_3_deq,
// 			       next_3_notEmpty,
// 			       set_verbosity );
// schedule next_0_notEmpty  SB ( next_0_deq );
//
// schedule next_1_first  CF ( prev_0_enq,
// 			    prev_0_notFull,
// 			    prev_1_enq,
// 			    prev_1_notFull,
// 			    prev_2_enq,
// 			    prev_2_notFull,
// 			    prev_3_enq,
// 			    prev_3_notFull,
// 			    next_0_first,
// 			    next_0_deq,
// 			    next_0_notEmpty,
// 			    next_1_first,
// 			    next_1_notEmpty,
// 			    next_2_first,
// 			    next_2_deq,
// 			    next_2_notEmpty,
// 			    next_3_first,
// 			    next_3_deq,
// 			    next_3_notEmpty,
// 			    set_verbosity );
// schedule next_1_first  SB ( next_1_deq );
//
// schedule next_1_deq  CF ( prev_0_enq,
// 			  prev_0_notFull,
// 			  prev_1_enq,
// 			  prev_1_notFull,
// 			  prev_2_enq,
// 			  prev_2_notFull,
// 			  prev_3_enq,
// 			  prev_3_notFull,
// 			  next_0_first,
// 			  next_0_deq,
// 			  next_0_notEmpty,
// 			  next_2_first,
// 			  next_2_deq,
// 			  next_2_notEmpty,
// 			  next_3_first,
// 			  next_3_deq,
// 			  next_3_notEmpty,
// 			  set_verbosity );
// schedule next_1_deq  C ( next_1_deq );
//
// schedule next_1_notEmpty  CF ( prev_0_enq,
// 			       prev_0_notFull,
// 			       prev_1_enq,
// 			       prev_1_notFull,
// 			       prev_2_enq,
// 			       prev_2_notFull,
// 			       prev_3_enq,
// 			       prev_3_notFull,
// 			       next_0_first,
// 			       next_0_deq,
// 			       next_0_notEmpty,
// 			       next_1_first,
// 			       next_1_notEmpty,
// 			       next_2_first,
// 			       next_2_deq,
// 			       next_2_notEmpty,
// 			       next_3_first,
// 			       next_3_deq,
// 			       next_3_notEmpty,
// 			       set_verbosity );
// schedule next_1_notEmpty  SB ( next_1_deq );
//
// schedule next_2_first  CF ( prev_0_enq,
// 			    prev_0_notFull,
// 			    prev_1_enq,
// 			    prev_1_notFull,
// 			    prev_2_enq,
// 			    prev_2_notFull,
// 			    prev_3_enq,
// 			    prev_3_notFull,
// 			    next_0_first,
// 			    next_0_deq,
// 			    next_0_notEmpty,
// 			    next_1_first,
// 			    next_1_deq,
// 			    next_1_notEmpty,
// 			    next_2_first,
// 			    next_2_notEmpty,
// 			    next_3_first,
// 			    next_3_deq,
// 			    next_3_notEmpty,
// 			    set_verbosity );
// schedule next_2_first  SB ( next_2_deq );
//
// schedule next_2_deq  CF ( prev_0_enq,
// 			  prev_0_notFull,
// 			  prev_1_enq,
// 			  prev_1_notFull,
// 			  prev_2_enq,
// 			  prev_2_notFull,
// 			  prev_3_enq,
// 			  prev_3_notFull,
// 			  next_0_first,
// 			  next_0_deq,
// 			  next_0_notEmpty,
// 			  next_1_first,
// 			  next_1_deq,
// 			  next_1_notEmpty,
// 			  next_3_first,
// 			  next_3_deq,
// 			  next_3_notEmpty,
// 			  set_verbosity );
// schedule next_2_deq  C ( next_2_deq );
//
// schedule next_2_notEmpty  CF ( prev_0_enq,
// 			       prev_0_notFull,
// 			       prev_1_enq,
// 			       prev_1_notFull,
// 			       prev_2_enq,
// 			       prev_2_notFull,
// 			       prev_3_enq,
// 			       prev_3_notFull,
// 			       next_0_first,
// 			       next_0_deq,
// 			       next_0_notEmpty,
// 			       next_1_first,
// 			       next_1_deq,
// 			       next_1_notEmpty,
// 			       next_2_first,
// 			       next_2_notEmpty,
// 			       next_3_first,
// 			       next_3_deq,
// 			       next_3_notEmpty,
// 			       set_verbosity );
// schedule next_2_notEmpty  SB ( next_2_deq );
//
// schedule next_3_first  CF ( prev_0_enq,
// 			    prev_0_notFull,
// 			    prev_1_enq,
// 			    prev_1_notFull,
// 			    prev_2_enq,
// 			    prev_2_notFull,
// 			    prev_3_enq,
// 			    prev_3_notFull,
// 			    next_0_first,
// 			    next_0_deq,
// 			    next_0_notEmpty,
// 			    next_1_first,
// 			    next_1_deq,
// 			    next_1_notEmpty,
// 			    next_2_first,
// 			    next_2_deq,
// 			    next_2_notEmpty,
// 			    next_3_first,
// 			    next_3_notEmpty,
// 			    set_verbosity );
// schedule next_3_first  SB ( next_3_deq );
//
// schedule next_3_deq  CF ( prev_0_enq,
// 			  prev_0_notFull,
// 			  prev_1_enq,
// 			  prev_1_notFull,
// 			  prev_2_enq,
// 			  prev_2_notFull,
// 			  prev_3_enq,
// 			  prev_3_notFull,
// 			  next_0_first,
// 			  next_0_deq,
// 			  next_0_notEmpty,
// 			  next_1_first,
// 			  next_1_deq,
// 			  next_1_notEmpty,
// 			  next_2_first,
// 			  next_2_deq,
// 			  next_2_notEmpty,
// 			  set_verbosity );
// schedule next_3_deq  C ( next_3_deq );
//
// schedule next_3_notEmpty  CF ( prev_0_enq,
// 			       prev_0_notFull,
// 			       prev_1_enq,
// 			       prev_1_notFull,
// 			       prev_2_enq,
// 			       prev_2_notFull,
// 			       prev_3_enq,
// 			       prev_3_notFull,
// 			       next_0_first,
// 			       next_0_deq,
// 			       next_0_notEmpty,
// 			       next_1_first,
// 			       next_1_deq,
// 			       next_1_notEmpty,
// 			       next_2_first,
// 			       next_2_deq,
// 			       next_2_notEmpty,
// 			       next_3_first,
// 			       next_3_notEmpty,
// 			       set_verbosity );
// schedule next_3_notEmpty  SB ( next_3_deq );
//
// schedule set_verbosity  CF ( prev_0_enq,
// 			     prev_0_notFull,
// 			     prev_1_enq,
// 			     prev_1_notFull,
// 			     prev_2_enq,
// 			     prev_2_notFull,
// 			     prev_3_enq,
// 			     prev_3_notFull,
// 			     next_0_first,
// 			     next_0_deq,
// 			     next_0_notEmpty,
// 			     next_1_first,
// 			     next_1_deq,
// 			     next_1_notEmpty,
// 			     next_2_first,
// 			     next_2_deq,
// 			     next_2_notEmpty,
// 			     next_3_first,
// 			     next_3_deq,
// 			     next_3_notEmpty );
// schedule set_verbosity  SBR ( set_verbosity );
//
//
// Ports:
// Name                         I/O  size props
// RDY_prev_0_enq                 O     1 reg
// prev_0_notFull                 O     1 reg
// RDY_prev_0_notFull             O     1 const
// RDY_prev_1_enq                 O     1 reg
// prev_1_notFull                 O     1 reg
// RDY_prev_1_notFull             O     1 const
// RDY_prev_2_enq                 O     1 reg
// prev_2_notFull                 O     1 reg
// RDY_prev_2_notFull             O     1 const
// RDY_prev_3_enq                 O     1 reg
// prev_3_notFull                 O     1 reg
// RDY_prev_3_notFull             O     1 const
// next_0_first                   O  1457 reg
// RDY_next_0_first               O     1 reg
// RDY_next_0_deq                 O     1 reg
// next_0_notEmpty                O     1 reg
// RDY_next_0_notEmpty            O     1 const
// next_1_first                   O  1457 reg
// RDY_next_1_first               O     1 reg
// RDY_next_1_deq                 O     1 reg
// next_1_notEmpty                O     1 reg
// RDY_next_1_notEmpty            O     1 const
// next_2_first                   O  1457 reg
// RDY_next_2_first               O     1 reg
// RDY_next_2_deq                 O     1 reg
// next_2_notEmpty                O     1 reg
// RDY_next_2_notEmpty            O     1 const
// next_3_first                   O  1457 reg
// RDY_next_3_first               O     1 reg
// RDY_next_3_deq                 O     1 reg
// next_3_notEmpty                O     1 reg
// RDY_next_3_notEmpty            O     1 const
// RDY_set_verbosity              O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// prev_0_enq_v                   I  1457 reg
// prev_1_enq_v                   I  1457 reg
// prev_2_enq_v                   I  1457 reg
// prev_3_enq_v                   I  1457 reg
// set_verbosity_verbosity        I    32 reg
// EN_prev_0_enq                  I     1
// EN_prev_1_enq                  I     1
// EN_prev_2_enq                  I     1
// EN_prev_3_enq                  I     1
// EN_next_0_deq                  I     1
// EN_next_1_deq                  I     1
// EN_next_2_deq                  I     1
// EN_next_3_deq                  I     1
// EN_set_verbosity               I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkProgram_1_1_1_2(CLK,
			 RST_N,

			 prev_0_enq_v,
			 EN_prev_0_enq,
			 RDY_prev_0_enq,

			 prev_0_notFull,
			 RDY_prev_0_notFull,

			 prev_1_enq_v,
			 EN_prev_1_enq,
			 RDY_prev_1_enq,

			 prev_1_notFull,
			 RDY_prev_1_notFull,

			 prev_2_enq_v,
			 EN_prev_2_enq,
			 RDY_prev_2_enq,

			 prev_2_notFull,
			 RDY_prev_2_notFull,

			 prev_3_enq_v,
			 EN_prev_3_enq,
			 RDY_prev_3_enq,

			 prev_3_notFull,
			 RDY_prev_3_notFull,

			 next_0_first,
			 RDY_next_0_first,

			 EN_next_0_deq,
			 RDY_next_0_deq,

			 next_0_notEmpty,
			 RDY_next_0_notEmpty,

			 next_1_first,
			 RDY_next_1_first,

			 EN_next_1_deq,
			 RDY_next_1_deq,

			 next_1_notEmpty,
			 RDY_next_1_notEmpty,

			 next_2_first,
			 RDY_next_2_first,

			 EN_next_2_deq,
			 RDY_next_2_deq,

			 next_2_notEmpty,
			 RDY_next_2_notEmpty,

			 next_3_first,
			 RDY_next_3_first,

			 EN_next_3_deq,
			 RDY_next_3_deq,

			 next_3_notEmpty,
			 RDY_next_3_notEmpty,

			 set_verbosity_verbosity,
			 EN_set_verbosity,
			 RDY_set_verbosity);
  input  CLK;
  input  RST_N;

  // action method prev_0_enq
  input  [1456 : 0] prev_0_enq_v;
  input  EN_prev_0_enq;
  output RDY_prev_0_enq;

  // value method prev_0_notFull
  output prev_0_notFull;
  output RDY_prev_0_notFull;

  // action method prev_1_enq
  input  [1456 : 0] prev_1_enq_v;
  input  EN_prev_1_enq;
  output RDY_prev_1_enq;

  // value method prev_1_notFull
  output prev_1_notFull;
  output RDY_prev_1_notFull;

  // action method prev_2_enq
  input  [1456 : 0] prev_2_enq_v;
  input  EN_prev_2_enq;
  output RDY_prev_2_enq;

  // value method prev_2_notFull
  output prev_2_notFull;
  output RDY_prev_2_notFull;

  // action method prev_3_enq
  input  [1456 : 0] prev_3_enq_v;
  input  EN_prev_3_enq;
  output RDY_prev_3_enq;

  // value method prev_3_notFull
  output prev_3_notFull;
  output RDY_prev_3_notFull;

  // value method next_0_first
  output [1456 : 0] next_0_first;
  output RDY_next_0_first;

  // action method next_0_deq
  input  EN_next_0_deq;
  output RDY_next_0_deq;

  // value method next_0_notEmpty
  output next_0_notEmpty;
  output RDY_next_0_notEmpty;

  // value method next_1_first
  output [1456 : 0] next_1_first;
  output RDY_next_1_first;

  // action method next_1_deq
  input  EN_next_1_deq;
  output RDY_next_1_deq;

  // value method next_1_notEmpty
  output next_1_notEmpty;
  output RDY_next_1_notEmpty;

  // value method next_2_first
  output [1456 : 0] next_2_first;
  output RDY_next_2_first;

  // action method next_2_deq
  input  EN_next_2_deq;
  output RDY_next_2_deq;

  // value method next_2_notEmpty
  output next_2_notEmpty;
  output RDY_next_2_notEmpty;

  // value method next_3_first
  output [1456 : 0] next_3_first;
  output RDY_next_3_first;

  // action method next_3_deq
  input  EN_next_3_deq;
  output RDY_next_3_deq;

  // value method next_3_notEmpty
  output next_3_notEmpty;
  output RDY_next_3_notEmpty;

  // action method set_verbosity
  input  [31 : 0] set_verbosity_verbosity;
  input  EN_set_verbosity;
  output RDY_set_verbosity;

  // signals for module outputs
  wire [1456 : 0] next_0_first, next_1_first, next_2_first, next_3_first;
  wire RDY_next_0_deq,
       RDY_next_0_first,
       RDY_next_0_notEmpty,
       RDY_next_1_deq,
       RDY_next_1_first,
       RDY_next_1_notEmpty,
       RDY_next_2_deq,
       RDY_next_2_first,
       RDY_next_2_notEmpty,
       RDY_next_3_deq,
       RDY_next_3_first,
       RDY_next_3_notEmpty,
       RDY_prev_0_enq,
       RDY_prev_0_notFull,
       RDY_prev_1_enq,
       RDY_prev_1_notFull,
       RDY_prev_2_enq,
       RDY_prev_2_notFull,
       RDY_prev_3_enq,
       RDY_prev_3_notFull,
       RDY_set_verbosity,
       next_0_notEmpty,
       next_1_notEmpty,
       next_2_notEmpty,
       next_3_notEmpty,
       prev_0_notFull,
       prev_1_notFull,
       prev_2_notFull,
       prev_3_notFull;

  // register cf_verbosity
  reg [31 : 0] cf_verbosity;
  wire [31 : 0] cf_verbosity_D_IN;
  wire cf_verbosity_EN;

  // register egress_cf_verbosity
  reg [31 : 0] egress_cf_verbosity;
  wire [31 : 0] egress_cf_verbosity_D_IN;
  wire egress_cf_verbosity_EN;

  // register ingress_cf_verbosity
  reg [31 : 0] ingress_cf_verbosity;
  wire [31 : 0] ingress_cf_verbosity_D_IN;
  wire ingress_cf_verbosity_EN;

  // ports of submodule demux_rv_buff_0_0_0
  wire [1458 : 0] demux_rv_buff_0_0_0_D_IN, demux_rv_buff_0_0_0_D_OUT;
  wire demux_rv_buff_0_0_0_CLR,
       demux_rv_buff_0_0_0_DEQ,
       demux_rv_buff_0_0_0_EMPTY_N,
       demux_rv_buff_0_0_0_ENQ,
       demux_rv_buff_0_0_0_FULL_N;

  // ports of submodule demux_rv_buff_0_0_1
  wire [1458 : 0] demux_rv_buff_0_0_1_D_IN, demux_rv_buff_0_0_1_D_OUT;
  wire demux_rv_buff_0_0_1_CLR,
       demux_rv_buff_0_0_1_DEQ,
       demux_rv_buff_0_0_1_EMPTY_N,
       demux_rv_buff_0_0_1_ENQ,
       demux_rv_buff_0_0_1_FULL_N;

  // ports of submodule demux_rv_buff_0_0_2
  wire [1458 : 0] demux_rv_buff_0_0_2_D_IN, demux_rv_buff_0_0_2_D_OUT;
  wire demux_rv_buff_0_0_2_CLR,
       demux_rv_buff_0_0_2_DEQ,
       demux_rv_buff_0_0_2_EMPTY_N,
       demux_rv_buff_0_0_2_ENQ,
       demux_rv_buff_0_0_2_FULL_N;

  // ports of submodule demux_rv_buff_0_0_3
  wire [1458 : 0] demux_rv_buff_0_0_3_D_IN, demux_rv_buff_0_0_3_D_OUT;
  wire demux_rv_buff_0_0_3_CLR,
       demux_rv_buff_0_0_3_DEQ,
       demux_rv_buff_0_0_3_EMPTY_N,
       demux_rv_buff_0_0_3_ENQ,
       demux_rv_buff_0_0_3_FULL_N;

  // ports of submodule egress_entry_req_ff
  wire [1456 : 0] egress_entry_req_ff_D_IN, egress_entry_req_ff_D_OUT;
  wire egress_entry_req_ff_CLR,
       egress_entry_req_ff_DEQ,
       egress_entry_req_ff_EMPTY_N,
       egress_entry_req_ff_ENQ,
       egress_entry_req_ff_FULL_N;

  // ports of submodule egress_entry_rsp_ff
  wire [1456 : 0] egress_entry_rsp_ff_D_IN;
  wire egress_entry_rsp_ff_CLR,
       egress_entry_rsp_ff_DEQ,
       egress_entry_rsp_ff_ENQ;

  // ports of submodule egress_exit_req_ff
  wire [1456 : 0] egress_exit_req_ff_D_IN, egress_exit_req_ff_D_OUT;
  wire egress_exit_req_ff_CLR,
       egress_exit_req_ff_DEQ,
       egress_exit_req_ff_EMPTY_N,
       egress_exit_req_ff_ENQ,
       egress_exit_req_ff_FULL_N;

  // ports of submodule egress_exit_rsp_ff
  wire [1456 : 0] egress_exit_rsp_ff_D_IN;
  wire egress_exit_rsp_ff_CLR, egress_exit_rsp_ff_DEQ, egress_exit_rsp_ff_ENQ;

  // ports of submodule funnel_ff_0
  wire [1456 : 0] funnel_ff_0_D_IN, funnel_ff_0_D_OUT;
  wire funnel_ff_0_CLR,
       funnel_ff_0_DEQ,
       funnel_ff_0_EMPTY_N,
       funnel_ff_0_ENQ,
       funnel_ff_0_FULL_N;

  // ports of submodule funnel_ff_1
  wire [1456 : 0] funnel_ff_1_D_IN, funnel_ff_1_D_OUT;
  wire funnel_ff_1_CLR,
       funnel_ff_1_DEQ,
       funnel_ff_1_EMPTY_N,
       funnel_ff_1_ENQ,
       funnel_ff_1_FULL_N;

  // ports of submodule funnel_ff_2
  wire [1456 : 0] funnel_ff_2_D_IN, funnel_ff_2_D_OUT;
  wire funnel_ff_2_CLR,
       funnel_ff_2_DEQ,
       funnel_ff_2_EMPTY_N,
       funnel_ff_2_ENQ,
       funnel_ff_2_FULL_N;

  // ports of submodule funnel_ff_3
  wire [1456 : 0] funnel_ff_3_D_IN, funnel_ff_3_D_OUT;
  wire funnel_ff_3_CLR,
       funnel_ff_3_DEQ,
       funnel_ff_3_EMPTY_N,
       funnel_ff_3_ENQ,
       funnel_ff_3_FULL_N;

  // ports of submodule ingress_entry_req_ff
  wire [1456 : 0] ingress_entry_req_ff_D_IN, ingress_entry_req_ff_D_OUT;
  wire ingress_entry_req_ff_CLR,
       ingress_entry_req_ff_DEQ,
       ingress_entry_req_ff_EMPTY_N,
       ingress_entry_req_ff_ENQ,
       ingress_entry_req_ff_FULL_N;

  // ports of submodule ingress_entry_rsp_ff
  wire [1456 : 0] ingress_entry_rsp_ff_D_IN;
  wire ingress_entry_rsp_ff_CLR,
       ingress_entry_rsp_ff_DEQ,
       ingress_entry_rsp_ff_ENQ;

  // ports of submodule ingress_exit_req_ff
  wire [1456 : 0] ingress_exit_req_ff_D_IN, ingress_exit_req_ff_D_OUT;
  wire ingress_exit_req_ff_CLR,
       ingress_exit_req_ff_DEQ,
       ingress_exit_req_ff_EMPTY_N,
       ingress_exit_req_ff_ENQ,
       ingress_exit_req_ff_FULL_N;

  // ports of submodule ingress_exit_rsp_ff
  wire [1456 : 0] ingress_exit_rsp_ff_D_IN;
  wire ingress_exit_rsp_ff_CLR,
       ingress_exit_rsp_ff_DEQ,
       ingress_exit_rsp_ff_ENQ;

  // ports of submodule metaPipe_buffs_0_0
  wire [1456 : 0] metaPipe_buffs_0_0_D_IN, metaPipe_buffs_0_0_D_OUT;
  wire metaPipe_buffs_0_0_CLR,
       metaPipe_buffs_0_0_DEQ,
       metaPipe_buffs_0_0_EMPTY_N,
       metaPipe_buffs_0_0_ENQ,
       metaPipe_buffs_0_0_FULL_N;

  // ports of submodule metaPipe_buffs_0_1
  wire [1456 : 0] metaPipe_buffs_0_1_D_IN;
  wire metaPipe_buffs_0_1_CLR, metaPipe_buffs_0_1_DEQ, metaPipe_buffs_0_1_ENQ;

  // ports of submodule metaPipe_buffs_0_2
  wire [1456 : 0] metaPipe_buffs_0_2_D_IN;
  wire metaPipe_buffs_0_2_CLR, metaPipe_buffs_0_2_DEQ, metaPipe_buffs_0_2_ENQ;

  // ports of submodule metaPipe_buffs_0_3
  wire [1456 : 0] metaPipe_buffs_0_3_D_IN;
  wire metaPipe_buffs_0_3_CLR, metaPipe_buffs_0_3_DEQ, metaPipe_buffs_0_3_ENQ;

  // ports of submodule writeData
  wire [1458 : 0] writeData_D_IN, writeData_D_OUT;
  wire writeData_CLR,
       writeData_DEQ,
       writeData_EMPTY_N,
       writeData_ENQ,
       writeData_FULL_N;

  // remaining internal signals
  wire [835 : 0] IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d245;
  wire [555 : 0] IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d244;
  wire [361 : 0] IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d784;
  wire [341 : 0] IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d783;
  wire [322 : 0] IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d165,
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d166;
  wire [275 : 0] IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d782;
  wire [256 : 0] IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d781;
  wire [190 : 0] IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d780;
  wire [163 : 0] IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d126,
		 IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d210;
  wire [162 : 0] IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d122,
		 IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d206,
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d123,
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d207;
  wire [137 : 0] IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d779;
  wire [114 : 0] IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d78,
		 IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d343,
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d79;
  wire [112 : 0] IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d277;
  wire [111 : 0] IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d273,
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d274;
  wire [103 : 0] IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d308,
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d309;
  wire [68 : 0] IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d778;
  wire [67 : 0] IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d243;
  wire [66 : 0] IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d239,
		IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d240;
  wire [48 : 0] IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d675;
  wire [47 : 0] IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d671,
		IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d672;
  wire [32 : 0] IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d471,
		IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d573,
		IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d624;
  wire [31 : 0] IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d442,
		IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d467,
		IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d544,
		IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d569,
		IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d620,
		IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d697,
		IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d443,
		IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d468,
		IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d545,
		IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d570,
		IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d621,
		IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d698;
  wire [20 : 0] IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d48,
		IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d49;
  wire [18 : 0] IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d595,
		IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d646,
		IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d777,
		IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d596,
		IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d647;
  wire [16 : 0] IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d522,
		IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d726;
  wire [15 : 0] IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d518,
		IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d722,
		IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d773,
		IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d519,
		IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d723,
		IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d774;
  wire [9 : 0] IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d369,
	       IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d420;
  wire [8 : 0] IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d339,
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d365,
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d391,
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d416,
	       IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d340,
	       IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d366,
	       IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d392,
	       IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d417;
  wire IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d132,
       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d174,
       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d216,
       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d251,
       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d283,
       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d317,
       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d349,
       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d375,
       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d400,
       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d426,
       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d451,
       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d477,
       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d493,
       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d502,
       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d528,
       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d553,
       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d56,
       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d579,
       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d604,
       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d630,
       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d655,
       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d681,
       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d706,
       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d732,
       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d748,
       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d757,
       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d87,
       IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d133,
       IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d175,
       IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d217,
       IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d252,
       IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d284,
       IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d318,
       IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d350,
       IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d376,
       IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d401,
       IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d427,
       IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d452,
       IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d478,
       IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d494,
       IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d503,
       IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d529,
       IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d554,
       IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d57,
       IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d580,
       IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d605,
       IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d631,
       IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d656,
       IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d682,
       IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d707,
       IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d733,
       IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d749,
       IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d758,
       IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d88,
       NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34,
       funnel_ff_1_notEmpty_OR_funnel_ff_0_notEmpty_0_ETC___d28;

  // action method prev_0_enq
  assign RDY_prev_0_enq = funnel_ff_0_FULL_N ;

  // value method prev_0_notFull
  assign prev_0_notFull = funnel_ff_0_FULL_N ;
  assign RDY_prev_0_notFull = 1'd1 ;

  // action method prev_1_enq
  assign RDY_prev_1_enq = funnel_ff_1_FULL_N ;

  // value method prev_1_notFull
  assign prev_1_notFull = funnel_ff_1_FULL_N ;
  assign RDY_prev_1_notFull = 1'd1 ;

  // action method prev_2_enq
  assign RDY_prev_2_enq = funnel_ff_2_FULL_N ;

  // value method prev_2_notFull
  assign prev_2_notFull = funnel_ff_2_FULL_N ;
  assign RDY_prev_2_notFull = 1'd1 ;

  // action method prev_3_enq
  assign RDY_prev_3_enq = funnel_ff_3_FULL_N ;

  // value method prev_3_notFull
  assign prev_3_notFull = funnel_ff_3_FULL_N ;
  assign RDY_prev_3_notFull = 1'd1 ;

  // value method next_0_first
  assign next_0_first = demux_rv_buff_0_0_0_D_OUT[1456:0] ;
  assign RDY_next_0_first = demux_rv_buff_0_0_0_EMPTY_N ;

  // action method next_0_deq
  assign RDY_next_0_deq = demux_rv_buff_0_0_0_EMPTY_N ;

  // value method next_0_notEmpty
  assign next_0_notEmpty = demux_rv_buff_0_0_0_EMPTY_N ;
  assign RDY_next_0_notEmpty = 1'd1 ;

  // value method next_1_first
  assign next_1_first = demux_rv_buff_0_0_1_D_OUT[1456:0] ;
  assign RDY_next_1_first = demux_rv_buff_0_0_1_EMPTY_N ;

  // action method next_1_deq
  assign RDY_next_1_deq = demux_rv_buff_0_0_1_EMPTY_N ;

  // value method next_1_notEmpty
  assign next_1_notEmpty = demux_rv_buff_0_0_1_EMPTY_N ;
  assign RDY_next_1_notEmpty = 1'd1 ;

  // value method next_2_first
  assign next_2_first = demux_rv_buff_0_0_2_D_OUT[1456:0] ;
  assign RDY_next_2_first = demux_rv_buff_0_0_2_EMPTY_N ;

  // action method next_2_deq
  assign RDY_next_2_deq = demux_rv_buff_0_0_2_EMPTY_N ;

  // value method next_2_notEmpty
  assign next_2_notEmpty = demux_rv_buff_0_0_2_EMPTY_N ;
  assign RDY_next_2_notEmpty = 1'd1 ;

  // value method next_3_first
  assign next_3_first = demux_rv_buff_0_0_3_D_OUT[1456:0] ;
  assign RDY_next_3_first = demux_rv_buff_0_0_3_EMPTY_N ;

  // action method next_3_deq
  assign RDY_next_3_deq = demux_rv_buff_0_0_3_EMPTY_N ;

  // value method next_3_notEmpty
  assign next_3_notEmpty = demux_rv_buff_0_0_3_EMPTY_N ;
  assign RDY_next_3_notEmpty = 1'd1 ;

  // action method set_verbosity
  assign RDY_set_verbosity = 1'd1 ;

  // submodule demux_rv_buff_0_0_0
  FIFO2 #(.width(32'd1459), .guarded(32'd1)) demux_rv_buff_0_0_0(.RST(RST_N),
								 .CLK(CLK),
								 .D_IN(demux_rv_buff_0_0_0_D_IN),
								 .ENQ(demux_rv_buff_0_0_0_ENQ),
								 .DEQ(demux_rv_buff_0_0_0_DEQ),
								 .CLR(demux_rv_buff_0_0_0_CLR),
								 .D_OUT(demux_rv_buff_0_0_0_D_OUT),
								 .FULL_N(demux_rv_buff_0_0_0_FULL_N),
								 .EMPTY_N(demux_rv_buff_0_0_0_EMPTY_N));

  // submodule demux_rv_buff_0_0_1
  FIFO2 #(.width(32'd1459), .guarded(32'd1)) demux_rv_buff_0_0_1(.RST(RST_N),
								 .CLK(CLK),
								 .D_IN(demux_rv_buff_0_0_1_D_IN),
								 .ENQ(demux_rv_buff_0_0_1_ENQ),
								 .DEQ(demux_rv_buff_0_0_1_DEQ),
								 .CLR(demux_rv_buff_0_0_1_CLR),
								 .D_OUT(demux_rv_buff_0_0_1_D_OUT),
								 .FULL_N(demux_rv_buff_0_0_1_FULL_N),
								 .EMPTY_N(demux_rv_buff_0_0_1_EMPTY_N));

  // submodule demux_rv_buff_0_0_2
  FIFO2 #(.width(32'd1459), .guarded(32'd1)) demux_rv_buff_0_0_2(.RST(RST_N),
								 .CLK(CLK),
								 .D_IN(demux_rv_buff_0_0_2_D_IN),
								 .ENQ(demux_rv_buff_0_0_2_ENQ),
								 .DEQ(demux_rv_buff_0_0_2_DEQ),
								 .CLR(demux_rv_buff_0_0_2_CLR),
								 .D_OUT(demux_rv_buff_0_0_2_D_OUT),
								 .FULL_N(demux_rv_buff_0_0_2_FULL_N),
								 .EMPTY_N(demux_rv_buff_0_0_2_EMPTY_N));

  // submodule demux_rv_buff_0_0_3
  FIFO2 #(.width(32'd1459), .guarded(32'd1)) demux_rv_buff_0_0_3(.RST(RST_N),
								 .CLK(CLK),
								 .D_IN(demux_rv_buff_0_0_3_D_IN),
								 .ENQ(demux_rv_buff_0_0_3_ENQ),
								 .DEQ(demux_rv_buff_0_0_3_DEQ),
								 .CLR(demux_rv_buff_0_0_3_CLR),
								 .D_OUT(demux_rv_buff_0_0_3_D_OUT),
								 .FULL_N(demux_rv_buff_0_0_3_FULL_N),
								 .EMPTY_N(demux_rv_buff_0_0_3_EMPTY_N));

  // submodule egress_entry_req_ff
  FIFO2 #(.width(32'd1457), .guarded(32'd1)) egress_entry_req_ff(.RST(RST_N),
								 .CLK(CLK),
								 .D_IN(egress_entry_req_ff_D_IN),
								 .ENQ(egress_entry_req_ff_ENQ),
								 .DEQ(egress_entry_req_ff_DEQ),
								 .CLR(egress_entry_req_ff_CLR),
								 .D_OUT(egress_entry_req_ff_D_OUT),
								 .FULL_N(egress_entry_req_ff_FULL_N),
								 .EMPTY_N(egress_entry_req_ff_EMPTY_N));

  // submodule egress_entry_rsp_ff
  FIFO2 #(.width(32'd1457), .guarded(32'd1)) egress_entry_rsp_ff(.RST(RST_N),
								 .CLK(CLK),
								 .D_IN(egress_entry_rsp_ff_D_IN),
								 .ENQ(egress_entry_rsp_ff_ENQ),
								 .DEQ(egress_entry_rsp_ff_DEQ),
								 .CLR(egress_entry_rsp_ff_CLR),
								 .D_OUT(),
								 .FULL_N(),
								 .EMPTY_N());

  // submodule egress_exit_req_ff
  FIFO2 #(.width(32'd1457), .guarded(32'd1)) egress_exit_req_ff(.RST(RST_N),
								.CLK(CLK),
								.D_IN(egress_exit_req_ff_D_IN),
								.ENQ(egress_exit_req_ff_ENQ),
								.DEQ(egress_exit_req_ff_DEQ),
								.CLR(egress_exit_req_ff_CLR),
								.D_OUT(egress_exit_req_ff_D_OUT),
								.FULL_N(egress_exit_req_ff_FULL_N),
								.EMPTY_N(egress_exit_req_ff_EMPTY_N));

  // submodule egress_exit_rsp_ff
  FIFO2 #(.width(32'd1457), .guarded(32'd1)) egress_exit_rsp_ff(.RST(RST_N),
								.CLK(CLK),
								.D_IN(egress_exit_rsp_ff_D_IN),
								.ENQ(egress_exit_rsp_ff_ENQ),
								.DEQ(egress_exit_rsp_ff_DEQ),
								.CLR(egress_exit_rsp_ff_CLR),
								.D_OUT(),
								.FULL_N(),
								.EMPTY_N());

  // submodule funnel_ff_0
  FIFO2 #(.width(32'd1457), .guarded(32'd1)) funnel_ff_0(.RST(RST_N),
							 .CLK(CLK),
							 .D_IN(funnel_ff_0_D_IN),
							 .ENQ(funnel_ff_0_ENQ),
							 .DEQ(funnel_ff_0_DEQ),
							 .CLR(funnel_ff_0_CLR),
							 .D_OUT(funnel_ff_0_D_OUT),
							 .FULL_N(funnel_ff_0_FULL_N),
							 .EMPTY_N(funnel_ff_0_EMPTY_N));

  // submodule funnel_ff_1
  FIFO2 #(.width(32'd1457), .guarded(32'd1)) funnel_ff_1(.RST(RST_N),
							 .CLK(CLK),
							 .D_IN(funnel_ff_1_D_IN),
							 .ENQ(funnel_ff_1_ENQ),
							 .DEQ(funnel_ff_1_DEQ),
							 .CLR(funnel_ff_1_CLR),
							 .D_OUT(funnel_ff_1_D_OUT),
							 .FULL_N(funnel_ff_1_FULL_N),
							 .EMPTY_N(funnel_ff_1_EMPTY_N));

  // submodule funnel_ff_2
  FIFO2 #(.width(32'd1457), .guarded(32'd1)) funnel_ff_2(.RST(RST_N),
							 .CLK(CLK),
							 .D_IN(funnel_ff_2_D_IN),
							 .ENQ(funnel_ff_2_ENQ),
							 .DEQ(funnel_ff_2_DEQ),
							 .CLR(funnel_ff_2_CLR),
							 .D_OUT(funnel_ff_2_D_OUT),
							 .FULL_N(funnel_ff_2_FULL_N),
							 .EMPTY_N(funnel_ff_2_EMPTY_N));

  // submodule funnel_ff_3
  FIFO2 #(.width(32'd1457), .guarded(32'd1)) funnel_ff_3(.RST(RST_N),
							 .CLK(CLK),
							 .D_IN(funnel_ff_3_D_IN),
							 .ENQ(funnel_ff_3_ENQ),
							 .DEQ(funnel_ff_3_DEQ),
							 .CLR(funnel_ff_3_CLR),
							 .D_OUT(funnel_ff_3_D_OUT),
							 .FULL_N(funnel_ff_3_FULL_N),
							 .EMPTY_N(funnel_ff_3_EMPTY_N));

  // submodule ingress_entry_req_ff
  FIFO2 #(.width(32'd1457), .guarded(32'd1)) ingress_entry_req_ff(.RST(RST_N),
								  .CLK(CLK),
								  .D_IN(ingress_entry_req_ff_D_IN),
								  .ENQ(ingress_entry_req_ff_ENQ),
								  .DEQ(ingress_entry_req_ff_DEQ),
								  .CLR(ingress_entry_req_ff_CLR),
								  .D_OUT(ingress_entry_req_ff_D_OUT),
								  .FULL_N(ingress_entry_req_ff_FULL_N),
								  .EMPTY_N(ingress_entry_req_ff_EMPTY_N));

  // submodule ingress_entry_rsp_ff
  FIFO2 #(.width(32'd1457), .guarded(32'd1)) ingress_entry_rsp_ff(.RST(RST_N),
								  .CLK(CLK),
								  .D_IN(ingress_entry_rsp_ff_D_IN),
								  .ENQ(ingress_entry_rsp_ff_ENQ),
								  .DEQ(ingress_entry_rsp_ff_DEQ),
								  .CLR(ingress_entry_rsp_ff_CLR),
								  .D_OUT(),
								  .FULL_N(),
								  .EMPTY_N());

  // submodule ingress_exit_req_ff
  FIFO2 #(.width(32'd1457), .guarded(32'd1)) ingress_exit_req_ff(.RST(RST_N),
								 .CLK(CLK),
								 .D_IN(ingress_exit_req_ff_D_IN),
								 .ENQ(ingress_exit_req_ff_ENQ),
								 .DEQ(ingress_exit_req_ff_DEQ),
								 .CLR(ingress_exit_req_ff_CLR),
								 .D_OUT(ingress_exit_req_ff_D_OUT),
								 .FULL_N(ingress_exit_req_ff_FULL_N),
								 .EMPTY_N(ingress_exit_req_ff_EMPTY_N));

  // submodule ingress_exit_rsp_ff
  FIFO2 #(.width(32'd1457), .guarded(32'd1)) ingress_exit_rsp_ff(.RST(RST_N),
								 .CLK(CLK),
								 .D_IN(ingress_exit_rsp_ff_D_IN),
								 .ENQ(ingress_exit_rsp_ff_ENQ),
								 .DEQ(ingress_exit_rsp_ff_DEQ),
								 .CLR(ingress_exit_rsp_ff_CLR),
								 .D_OUT(),
								 .FULL_N(),
								 .EMPTY_N());

  // submodule metaPipe_buffs_0_0
  FIFO2 #(.width(32'd1457), .guarded(32'd1)) metaPipe_buffs_0_0(.RST(RST_N),
								.CLK(CLK),
								.D_IN(metaPipe_buffs_0_0_D_IN),
								.ENQ(metaPipe_buffs_0_0_ENQ),
								.DEQ(metaPipe_buffs_0_0_DEQ),
								.CLR(metaPipe_buffs_0_0_CLR),
								.D_OUT(metaPipe_buffs_0_0_D_OUT),
								.FULL_N(metaPipe_buffs_0_0_FULL_N),
								.EMPTY_N(metaPipe_buffs_0_0_EMPTY_N));

  // submodule metaPipe_buffs_0_1
  FIFO2 #(.width(32'd1457), .guarded(32'd1)) metaPipe_buffs_0_1(.RST(RST_N),
								.CLK(CLK),
								.D_IN(metaPipe_buffs_0_1_D_IN),
								.ENQ(metaPipe_buffs_0_1_ENQ),
								.DEQ(metaPipe_buffs_0_1_DEQ),
								.CLR(metaPipe_buffs_0_1_CLR),
								.D_OUT(),
								.FULL_N(),
								.EMPTY_N());

  // submodule metaPipe_buffs_0_2
  FIFO2 #(.width(32'd1457), .guarded(32'd1)) metaPipe_buffs_0_2(.RST(RST_N),
								.CLK(CLK),
								.D_IN(metaPipe_buffs_0_2_D_IN),
								.ENQ(metaPipe_buffs_0_2_ENQ),
								.DEQ(metaPipe_buffs_0_2_DEQ),
								.CLR(metaPipe_buffs_0_2_CLR),
								.D_OUT(),
								.FULL_N(),
								.EMPTY_N());

  // submodule metaPipe_buffs_0_3
  FIFO2 #(.width(32'd1457), .guarded(32'd1)) metaPipe_buffs_0_3(.RST(RST_N),
								.CLK(CLK),
								.D_IN(metaPipe_buffs_0_3_D_IN),
								.ENQ(metaPipe_buffs_0_3_ENQ),
								.DEQ(metaPipe_buffs_0_3_DEQ),
								.CLR(metaPipe_buffs_0_3_CLR),
								.D_OUT(),
								.FULL_N(),
								.EMPTY_N());

  // submodule writeData
  FIFO2 #(.width(32'd1459), .guarded(32'd1)) writeData(.RST(RST_N),
						       .CLK(CLK),
						       .D_IN(writeData_D_IN),
						       .ENQ(writeData_ENQ),
						       .DEQ(writeData_DEQ),
						       .CLR(writeData_CLR),
						       .D_OUT(writeData_D_OUT),
						       .FULL_N(writeData_FULL_N),
						       .EMPTY_N(writeData_EMPTY_N));

  // register cf_verbosity
  assign cf_verbosity_D_IN = set_verbosity_verbosity ;
  assign cf_verbosity_EN = EN_set_verbosity ;

  // register egress_cf_verbosity
  assign egress_cf_verbosity_D_IN = set_verbosity_verbosity ;
  assign egress_cf_verbosity_EN = EN_set_verbosity ;

  // register ingress_cf_verbosity
  assign ingress_cf_verbosity_D_IN = set_verbosity_verbosity ;
  assign ingress_cf_verbosity_EN = EN_set_verbosity ;

  // submodule demux_rv_buff_0_0_0
  assign demux_rv_buff_0_0_0_D_IN = { 2'd0, writeData_D_OUT[1456:0] } ;
  assign demux_rv_buff_0_0_0_ENQ =
	     writeData_EMPTY_N && demux_rv_buff_0_0_0_FULL_N &&
	     writeData_D_OUT[1458:1457] == 2'd0 ;
  assign demux_rv_buff_0_0_0_DEQ = EN_next_0_deq ;
  assign demux_rv_buff_0_0_0_CLR = 1'b0 ;

  // submodule demux_rv_buff_0_0_1
  assign demux_rv_buff_0_0_1_D_IN = demux_rv_buff_0_0_0_D_IN ;
  assign demux_rv_buff_0_0_1_ENQ =
	     writeData_EMPTY_N && demux_rv_buff_0_0_1_FULL_N &&
	     writeData_D_OUT[1458:1457] == 2'd1 ;
  assign demux_rv_buff_0_0_1_DEQ = EN_next_1_deq ;
  assign demux_rv_buff_0_0_1_CLR = 1'b0 ;

  // submodule demux_rv_buff_0_0_2
  assign demux_rv_buff_0_0_2_D_IN = demux_rv_buff_0_0_0_D_IN ;
  assign demux_rv_buff_0_0_2_ENQ =
	     writeData_EMPTY_N && demux_rv_buff_0_0_2_FULL_N &&
	     writeData_D_OUT[1458:1457] == 2'd2 ;
  assign demux_rv_buff_0_0_2_DEQ = EN_next_2_deq ;
  assign demux_rv_buff_0_0_2_CLR = 1'b0 ;

  // submodule demux_rv_buff_0_0_3
  assign demux_rv_buff_0_0_3_D_IN = demux_rv_buff_0_0_0_D_IN ;
  assign demux_rv_buff_0_0_3_ENQ =
	     writeData_EMPTY_N && demux_rv_buff_0_0_3_FULL_N &&
	     writeData_D_OUT[1458:1457] == 2'd3 ;
  assign demux_rv_buff_0_0_3_DEQ = EN_next_3_deq ;
  assign demux_rv_buff_0_0_3_CLR = 1'b0 ;

  // submodule egress_entry_req_ff
  assign egress_entry_req_ff_D_IN = ingress_exit_req_ff_D_OUT ;
  assign egress_entry_req_ff_ENQ =
	     ingress_exit_req_ff_EMPTY_N && egress_entry_req_ff_FULL_N ;
  assign egress_entry_req_ff_DEQ =
	     egress_entry_req_ff_EMPTY_N && egress_exit_req_ff_FULL_N ;
  assign egress_entry_req_ff_CLR = 1'b0 ;

  // submodule egress_entry_rsp_ff
  assign egress_entry_rsp_ff_D_IN = 1457'h0 ;
  assign egress_entry_rsp_ff_ENQ = 1'b0 ;
  assign egress_entry_rsp_ff_DEQ = 1'b0 ;
  assign egress_entry_rsp_ff_CLR = 1'b0 ;

  // submodule egress_exit_req_ff
  assign egress_exit_req_ff_D_IN = egress_entry_req_ff_D_OUT ;
  assign egress_exit_req_ff_ENQ =
	     egress_entry_req_ff_EMPTY_N && egress_exit_req_ff_FULL_N ;
  assign egress_exit_req_ff_DEQ =
	     egress_exit_req_ff_EMPTY_N &&
	     (!egress_exit_req_ff_D_OUT[371] || writeData_FULL_N) ;
  assign egress_exit_req_ff_CLR = 1'b0 ;

  // submodule egress_exit_rsp_ff
  assign egress_exit_rsp_ff_D_IN = 1457'h0 ;
  assign egress_exit_rsp_ff_ENQ = 1'b0 ;
  assign egress_exit_rsp_ff_DEQ = 1'b0 ;
  assign egress_exit_rsp_ff_CLR = 1'b0 ;

  // submodule funnel_ff_0
  assign funnel_ff_0_D_IN = prev_0_enq_v ;
  assign funnel_ff_0_ENQ = EN_prev_0_enq ;
  assign funnel_ff_0_DEQ =
	     funnel_ff_1_notEmpty_OR_funnel_ff_0_notEmpty_0_ETC___d28 &&
	     funnel_ff_0_EMPTY_N ;
  assign funnel_ff_0_CLR = 1'b0 ;

  // submodule funnel_ff_1
  assign funnel_ff_1_D_IN = prev_1_enq_v ;
  assign funnel_ff_1_ENQ = EN_prev_1_enq ;
  assign funnel_ff_1_DEQ =
	     funnel_ff_1_notEmpty_OR_funnel_ff_0_notEmpty_0_ETC___d28 &&
	     !funnel_ff_0_EMPTY_N &&
	     funnel_ff_1_EMPTY_N ;
  assign funnel_ff_1_CLR = 1'b0 ;

  // submodule funnel_ff_2
  assign funnel_ff_2_D_IN = prev_2_enq_v ;
  assign funnel_ff_2_ENQ = EN_prev_2_enq ;
  assign funnel_ff_2_DEQ =
	     funnel_ff_1_notEmpty_OR_funnel_ff_0_notEmpty_0_ETC___d28 &&
	     !funnel_ff_1_EMPTY_N &&
	     !funnel_ff_0_EMPTY_N &&
	     funnel_ff_2_EMPTY_N ;
  assign funnel_ff_2_CLR = 1'b0 ;

  // submodule funnel_ff_3
  assign funnel_ff_3_D_IN = prev_3_enq_v ;
  assign funnel_ff_3_ENQ = EN_prev_3_enq ;
  assign funnel_ff_3_DEQ =
	     funnel_ff_1_notEmpty_OR_funnel_ff_0_notEmpty_0_ETC___d28 &&
	     NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ;
  assign funnel_ff_3_CLR = 1'b0 ;

  // submodule ingress_entry_req_ff
  assign ingress_entry_req_ff_D_IN = metaPipe_buffs_0_0_D_OUT ;
  assign ingress_entry_req_ff_ENQ =
	     metaPipe_buffs_0_0_EMPTY_N && ingress_entry_req_ff_FULL_N ;
  assign ingress_entry_req_ff_DEQ =
	     ingress_entry_req_ff_EMPTY_N && ingress_exit_req_ff_FULL_N ;
  assign ingress_entry_req_ff_CLR = 1'b0 ;

  // submodule ingress_entry_rsp_ff
  assign ingress_entry_rsp_ff_D_IN = 1457'h0 ;
  assign ingress_entry_rsp_ff_ENQ = 1'b0 ;
  assign ingress_entry_rsp_ff_DEQ = 1'b0 ;
  assign ingress_entry_rsp_ff_CLR = 1'b0 ;

  // submodule ingress_exit_req_ff
  assign ingress_exit_req_ff_D_IN = ingress_entry_req_ff_D_OUT ;
  assign ingress_exit_req_ff_ENQ =
	     ingress_entry_req_ff_EMPTY_N && ingress_exit_req_ff_FULL_N ;
  assign ingress_exit_req_ff_DEQ =
	     ingress_exit_req_ff_EMPTY_N && egress_entry_req_ff_FULL_N ;
  assign ingress_exit_req_ff_CLR = 1'b0 ;

  // submodule ingress_exit_rsp_ff
  assign ingress_exit_rsp_ff_D_IN = 1457'h0 ;
  assign ingress_exit_rsp_ff_ENQ = 1'b0 ;
  assign ingress_exit_rsp_ff_DEQ = 1'b0 ;
  assign ingress_exit_rsp_ff_CLR = 1'b0 ;

  // submodule metaPipe_buffs_0_0
  assign metaPipe_buffs_0_0_D_IN =
	     { NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[1456:1436] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d49,
	       IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d245,
	       IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d277,
	       IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d343,
	       IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d369,
	       IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d784 } ;
  assign metaPipe_buffs_0_0_ENQ =
	     funnel_ff_1_notEmpty_OR_funnel_ff_0_notEmpty_0_ETC___d28 &&
	     (funnel_ff_3_EMPTY_N || funnel_ff_2_EMPTY_N ||
	      funnel_ff_1_EMPTY_N ||
	      funnel_ff_0_EMPTY_N) ;
  assign metaPipe_buffs_0_0_DEQ =
	     metaPipe_buffs_0_0_EMPTY_N && ingress_entry_req_ff_FULL_N ;
  assign metaPipe_buffs_0_0_CLR = 1'b0 ;

  // submodule metaPipe_buffs_0_1
  assign metaPipe_buffs_0_1_D_IN = 1457'h0 ;
  assign metaPipe_buffs_0_1_ENQ = 1'b0 ;
  assign metaPipe_buffs_0_1_DEQ = 1'b0 ;
  assign metaPipe_buffs_0_1_CLR = 1'b0 ;

  // submodule metaPipe_buffs_0_2
  assign metaPipe_buffs_0_2_D_IN = 1457'h0 ;
  assign metaPipe_buffs_0_2_ENQ = 1'b0 ;
  assign metaPipe_buffs_0_2_DEQ = 1'b0 ;
  assign metaPipe_buffs_0_2_CLR = 1'b0 ;

  // submodule metaPipe_buffs_0_3
  assign metaPipe_buffs_0_3_D_IN = 1457'h0 ;
  assign metaPipe_buffs_0_3_ENQ = 1'b0 ;
  assign metaPipe_buffs_0_3_DEQ = 1'b0 ;
  assign metaPipe_buffs_0_3_CLR = 1'b0 ;

  // submodule writeData
  assign writeData_D_IN =
	     { egress_exit_req_ff_D_OUT[363:362],
	       egress_exit_req_ff_D_OUT[1456:372],
	       1'd1,
	       egress_exit_req_ff_D_OUT[370:0] } ;
  assign writeData_ENQ =
	     egress_exit_req_ff_EMPTY_N &&
	     (!egress_exit_req_ff_D_OUT[371] || writeData_FULL_N) &&
	     egress_exit_req_ff_D_OUT[371] ;
  assign writeData_DEQ =
	     writeData_EMPTY_N && demux_rv_buff_0_0_3_FULL_N &&
	     writeData_D_OUT[1458:1457] == 2'd3 ||
	     writeData_EMPTY_N && demux_rv_buff_0_0_2_FULL_N &&
	     writeData_D_OUT[1458:1457] == 2'd2 ||
	     writeData_EMPTY_N && demux_rv_buff_0_0_1_FULL_N &&
	     writeData_D_OUT[1458:1457] == 2'd1 ||
	     writeData_EMPTY_N && demux_rv_buff_0_0_0_FULL_N &&
	     writeData_D_OUT[1458:1457] == 2'd0 ;
  assign writeData_CLR = 1'b0 ;

  // remaining internal signals
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d122 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[1318:1156] :
	       funnel_ff_0_D_OUT[1318:1156] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d132 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[1155] :
	       !funnel_ff_0_EMPTY_N || funnel_ff_0_D_OUT[1155] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d165 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[1154:832] :
	       funnel_ff_0_D_OUT[1154:832] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d174 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[831] :
	       !funnel_ff_0_EMPTY_N || funnel_ff_0_D_OUT[831] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d206 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[830:668] :
	       funnel_ff_0_D_OUT[830:668] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d216 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[667] :
	       !funnel_ff_0_EMPTY_N || funnel_ff_0_D_OUT[667] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d239 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[666:600] :
	       funnel_ff_0_D_OUT[666:600] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d251 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[599] :
	       !funnel_ff_0_EMPTY_N || funnel_ff_0_D_OUT[599] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d273 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[598:487] :
	       funnel_ff_0_D_OUT[598:487] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d283 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[486] :
	       !funnel_ff_0_EMPTY_N || funnel_ff_0_D_OUT[486] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d308 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[485:382] :
	       funnel_ff_0_D_OUT[485:382] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d317 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[381] :
	       !funnel_ff_0_EMPTY_N || funnel_ff_0_D_OUT[381] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d339 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[380:372] :
	       funnel_ff_0_D_OUT[380:372] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d349 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[371] :
	       !funnel_ff_0_EMPTY_N || funnel_ff_0_D_OUT[371] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d365 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[370:362] :
	       funnel_ff_0_D_OUT[370:362] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d375 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[361] :
	       !funnel_ff_0_EMPTY_N || funnel_ff_0_D_OUT[361] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d391 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[360:352] :
	       funnel_ff_0_D_OUT[360:352] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d400 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[351] :
	       !funnel_ff_0_EMPTY_N || funnel_ff_0_D_OUT[351] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d416 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[350:342] :
	       funnel_ff_0_D_OUT[350:342] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d426 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[341] :
	       !funnel_ff_0_EMPTY_N || funnel_ff_0_D_OUT[341] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d442 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[340:309] :
	       funnel_ff_0_D_OUT[340:309] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d451 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[308] :
	       !funnel_ff_0_EMPTY_N || funnel_ff_0_D_OUT[308] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d467 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[307:276] :
	       funnel_ff_0_D_OUT[307:276] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d477 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[275] :
	       !funnel_ff_0_EMPTY_N || funnel_ff_0_D_OUT[275] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d48 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[1456:1436] :
	       funnel_ff_0_D_OUT[1456:1436] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d493 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[274] :
	       funnel_ff_0_D_OUT[274] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d502 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[273] :
	       !funnel_ff_0_EMPTY_N || funnel_ff_0_D_OUT[273] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d518 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[272:257] :
	       funnel_ff_0_D_OUT[272:257] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d528 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[256] :
	       !funnel_ff_0_EMPTY_N || funnel_ff_0_D_OUT[256] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d544 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[255:224] :
	       funnel_ff_0_D_OUT[255:224] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d553 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[223] :
	       !funnel_ff_0_EMPTY_N || funnel_ff_0_D_OUT[223] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d56 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[1435] :
	       !funnel_ff_0_EMPTY_N || funnel_ff_0_D_OUT[1435] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d569 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[222:191] :
	       funnel_ff_0_D_OUT[222:191] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d579 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[190] :
	       !funnel_ff_0_EMPTY_N || funnel_ff_0_D_OUT[190] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d595 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[189:171] :
	       funnel_ff_0_D_OUT[189:171] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d604 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[170] :
	       !funnel_ff_0_EMPTY_N || funnel_ff_0_D_OUT[170] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d620 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[169:138] :
	       funnel_ff_0_D_OUT[169:138] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d630 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[137] :
	       !funnel_ff_0_EMPTY_N || funnel_ff_0_D_OUT[137] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d646 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[136:118] :
	       funnel_ff_0_D_OUT[136:118] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d655 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[117] :
	       !funnel_ff_0_EMPTY_N || funnel_ff_0_D_OUT[117] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d671 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[116:69] :
	       funnel_ff_0_D_OUT[116:69] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d681 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[68] :
	       !funnel_ff_0_EMPTY_N || funnel_ff_0_D_OUT[68] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d697 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[67:36] :
	       funnel_ff_0_D_OUT[67:36] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d706 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[35] :
	       !funnel_ff_0_EMPTY_N || funnel_ff_0_D_OUT[35] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d722 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[34:19] :
	       funnel_ff_0_D_OUT[34:19] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d732 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[18] :
	       !funnel_ff_0_EMPTY_N || funnel_ff_0_D_OUT[18] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d748 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[17] :
	       funnel_ff_0_D_OUT[17] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d757 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[16] :
	       !funnel_ff_0_EMPTY_N || funnel_ff_0_D_OUT[16] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d773 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[15:0] :
	       funnel_ff_0_D_OUT[15:0] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d78 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[1434:1320] :
	       funnel_ff_0_D_OUT[1434:1320] ;
  assign IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d87 =
	     (!funnel_ff_0_EMPTY_N && funnel_ff_1_EMPTY_N) ?
	       funnel_ff_1_D_OUT[1319] :
	       !funnel_ff_0_EMPTY_N || funnel_ff_0_D_OUT[1319] ;
  assign IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d126 =
	     { NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[1319] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d88,
	       NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[1318:1156] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d123 } ;
  assign IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d210 =
	     { NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[831] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d175,
	       NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[830:668] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d207 } ;
  assign IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d243 =
	     { NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[667] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d217,
	       NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[666:600] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d240 } ;
  assign IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d244 =
	     { NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[1155] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d133,
	       NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[1154:832] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d166,
	       IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d210,
	       IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d243 } ;
  assign IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d245 =
	     { NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[1435] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d57,
	       NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[1434:1320] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d79,
	       IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d126,
	       IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d244 } ;
  assign IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d277 =
	     { NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[599] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d252,
	       NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[598:487] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d274 } ;
  assign IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d343 =
	     { NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[486] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d284,
	       NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[485:382] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d309,
	       NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[381] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d318,
	       NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[380:372] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d340 } ;
  assign IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d369 =
	     { NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[371] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d350,
	       NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[370:362] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d366 } ;
  assign IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d420 =
	     { NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[351] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d401,
	       NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[350:342] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d417 } ;
  assign IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d471 =
	     { NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[308] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d452,
	       NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[307:276] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d468 } ;
  assign IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d522 =
	     { NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[273] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d503,
	       NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[272:257] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d519 } ;
  assign IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d573 =
	     { NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[223] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d554,
	       NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[222:191] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d570 } ;
  assign IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d624 =
	     { NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[170] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d605,
	       NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[169:138] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d621 } ;
  assign IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d675 =
	     { NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[117] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d656,
	       NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[116:69] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d672 } ;
  assign IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d726 =
	     { NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[35] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d707,
	       NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[34:19] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d723 } ;
  assign IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d777 =
	     { NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[18] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d733,
	       NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[17] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d749,
	       NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[16] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d758,
	       NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[15:0] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d774 } ;
  assign IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d778 =
	     { NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[68] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d682,
	       NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[67:36] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d698,
	       IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d726,
	       IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d777 } ;
  assign IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d779 =
	     { NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[137] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d631,
	       NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[136:118] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d647,
	       IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d675,
	       IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d778 } ;
  assign IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d780 =
	     { NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[190] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d580,
	       NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[189:171] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d596,
	       IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d624,
	       IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d779 } ;
  assign IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d781 =
	     { NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[256] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d529,
	       NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[255:224] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d545,
	       IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d573,
	       IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d780 } ;
  assign IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d782 =
	     { NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[275] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d478,
	       NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[274] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d494,
	       IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d522,
	       IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d781 } ;
  assign IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d783 =
	     { NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[341] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d427,
	       NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[340:309] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d443,
	       IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d471,
	       IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d782 } ;
  assign IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d784 =
	     { NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[361] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d376,
	       NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 ?
		 funnel_ff_3_D_OUT[360:352] :
		 IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d392,
	       IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d420,
	       IF_NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funne_ETC___d783 } ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d123 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[1318:1156] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d122 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d133 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[1155] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d132 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d166 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[1154:832] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d165 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d175 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[831] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d174 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d207 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[830:668] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d206 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d217 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[667] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d216 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d240 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[666:600] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d239 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d252 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[599] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d251 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d274 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[598:487] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d273 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d284 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[486] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d283 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d309 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[485:382] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d308 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d318 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[381] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d317 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d340 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[380:372] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d339 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d350 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[371] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d349 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d366 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[370:362] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d365 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d376 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[361] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d375 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d392 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[360:352] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d391 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d401 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[351] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d400 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d417 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[350:342] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d416 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d427 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[341] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d426 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d443 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[340:309] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d442 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d452 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[308] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d451 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d468 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[307:276] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d467 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d478 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[275] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d477 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d49 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[1456:1436] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d48 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d494 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[274] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d493 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d503 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[273] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d502 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d519 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[272:257] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d518 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d529 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[256] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d528 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d545 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[255:224] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d544 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d554 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[223] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d553 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d57 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[1435] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d56 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d570 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[222:191] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d569 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d580 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[190] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d579 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d596 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[189:171] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d595 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d605 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[170] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d604 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d621 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[169:138] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d620 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d631 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[137] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d630 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d647 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[136:118] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d646 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d656 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[117] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d655 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d672 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[116:69] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d671 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d682 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[68] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d681 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d698 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[67:36] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d697 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d707 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[35] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d706 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d723 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[34:19] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d722 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d733 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[18] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d732 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d749 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[17] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d748 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d758 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[16] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d757 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d774 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[15:0] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d773 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d79 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[1434:1320] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d78 ;
  assign IF_funnel_ff_0_notEmpty_OR_NOT_funnel_ff_1_not_ETC___d88 =
	     (!funnel_ff_1_EMPTY_N && !funnel_ff_0_EMPTY_N &&
	      funnel_ff_2_EMPTY_N) ?
	       funnel_ff_2_D_OUT[1319] :
	       IF_NOT_funnel_ff_0_notEmpty_AND_funnel_ff_1_no_ETC___d87 ;
  assign NOT_funnel_ff_2_notEmpty__1_2_AND_NOT_funnel_f_ETC___d34 =
	     !funnel_ff_2_EMPTY_N && !funnel_ff_1_EMPTY_N &&
	     !funnel_ff_0_EMPTY_N &&
	     funnel_ff_3_EMPTY_N ;
  assign funnel_ff_1_notEmpty_OR_funnel_ff_0_notEmpty_0_ETC___d28 =
	     !funnel_ff_3_EMPTY_N && !funnel_ff_2_EMPTY_N &&
	     !funnel_ff_1_EMPTY_N &&
	     !funnel_ff_0_EMPTY_N ||
	     metaPipe_buffs_0_0_FULL_N ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (cf_verbosity_EN)
      cf_verbosity <= `BSV_ASSIGNMENT_DELAY cf_verbosity_D_IN;
    if (egress_cf_verbosity_EN)
      egress_cf_verbosity <= `BSV_ASSIGNMENT_DELAY egress_cf_verbosity_D_IN;
    if (ingress_cf_verbosity_EN)
      ingress_cf_verbosity <= `BSV_ASSIGNMENT_DELAY ingress_cf_verbosity_D_IN;
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    cf_verbosity = 32'hAAAAAAAA;
    egress_cf_verbosity = 32'hAAAAAAAA;
    ingress_cf_verbosity = 32'hAAAAAAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkProgram_1_1_1_2

